# Site settings
author: Kate Pokrass
title: Data Science For The Greater Good
header-img: img/home-bg.png
email: kpokrass@gmail.com
copyright_name: Kate Pokrass
description: > # this means to ignore newlines until "baseurl:"
  Connecting the Details to the Big Picture
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kpokrass

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
